###
# GET : All notes
GET http://localhost:3000/api/notes HTTP/1.1
Content-Type: application/json

###
# POST : Create notes
POST http://localhost:3000/api/notes HTTP/1.1
Content-Type: application/json

{
  "judul": "Meeting Project",
  "isi": "Diskusi dengan tim jam 14.00 di Google Meet"
}

###
# PUT : Update notes
PUT http://localhost:3000/api/notes/1 HTTP/1.1
Content-Type: application/json

{
  "judul": "Jadwal Kuliah",
  "isi": "Senin - Pemrograman Web, Rabu - Basis Data"
}

###
# DELETE : Delete notes
DELETE http://localhost:3000/api/notes/6 HTTP/1.1
Content-Type: application/json