steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/notes-be-rest',
        '-f',
        'backend/Dockerfile',
        './backend'
      ]

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/notes-be-rest'
      ]

  # Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'notes-be-rest',
        '--image',
        'gcr.io/$PROJECT_ID/notes-be-rest',
        '--region',
        'asia-southeast2',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/notes-be-rest'